sudo: required

language: go

services:
  - docker

go:
  - 1.11.x
  - mast

install: true

env:
  - GO111MODULE=on

script:
  - go mod tidy
  - make test
  - make docker_test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f .cover/coverage.txt
